### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by fnordson** [mytourbook/mytourbook.github.io#2]
I've been using this program for quite a few years now and there is one thing I don't understand: 

Why can't it have normal update procedure like every normal program too?  
Why do I have to add update URLs for minor updates, and then there are those major updates which do not work through the updater at all?  
It doesn't make any sense to me.  
Is there some deeper reason for that?

**Comment by wolfgang-ch** [comment]
Installation/update is a very complex topic and in the last 15 years I spend many many weeks that the product file is created automatically, publishing/updating is another complex topic why I've not yet spent much time into it.
